#include <ranges>
#include <iostream>
#include <iomanip>
#include <fstream>
#include <random>
#include <vector>
#include <unordered_map>

#include <bitboard.hpp>
#include <board_utils.hpp>

using namespace bears_chess;

class MagicHash {
    public:
        using scale_t = std::underlying_type_t<Bitboard>;

        struct Stats {
            bool valid;
            uint64_t max_hash;
            bool mod_needed;
        };

        constexpr MagicHash(scale_t _scale, size_t _target_size) :
            scale(_scale), target_size(_target_size), shift(64 - log2(_target_size))
        {}

        template<bool ApplyMod=true>
        constexpr size_t apply(Bitboard bb_blockers) const {
            size_t hash = static_cast<size_t>((static_cast<scale_t>(bb_blockers) * scale) >> shift);
            if constexpr (ApplyMod) {
                hash %= target_size;
            }
            return hash;
        }

        Stats check_magic(const std::vector<MagicEntry>& attack_sets) const {
            std::unordered_map<std::size_t, Bitboard> hash_to_moves;

            Stats result{false, 0, false};
            for (const auto& attack_set : attack_sets) {
                size_t hash_nomod = apply<false>(attack_set.bb_blockers);
                size_t hash = hash_nomod % target_size;

                result.mod_needed = result.mod_needed || (hash != hash_nomod);

                if (hash_to_moves.count(hash)) {
                    // if the hash exists, ensure the moves are the same
                    if (hash_to_moves[hash] != attack_set.bb_moves)
                    result.valid = false;
                        return result;
                } else {
                    // otherwise, store the hash and the moves
                    hash_to_moves[hash] = attack_set.bb_moves;
                }
                result.max_hash = std::max(result.max_hash, hash);
            }

            result.valid = true;
            return result;
        }

        friend std::ostream& operator<<(std::ostream&, const MagicHash&);
    private:
        const scale_t scale{};
        const int8_t shift{};
        const size_t target_size{};
};

std::ostream& operator<<(std::ostream& out, const MagicHash& hash) {
    std::ios::fmtflags original_flags = out.flags();
    char original_fill = out.fill();

    out << "0x" << std::hex << std::setw(16) << std::setfill('0') << hash.scale << "ULL";

    out.flags(original_flags);
    out.fill(original_fill);

    return out;
}

MagicHash find_magic(const std::vector<MagicEntry>& attack_sets) {
    std::mt19937_64 rng(std::random_device{}());
    std::uniform_int_distribution<uint64_t> dist;

    size_t size = attack_sets.size();

    while (true) {
        MagicHash magic = MagicHash(dist(rng) & dist(rng) & dist(rng), size);
        MagicHash::Stats stats = magic.check_magic(attack_sets);
        if (stats.valid) {
            return magic;
        }
    }
}

static Bitboard assign_bits(Bitboard bb, uint64_t bits) {
    Bitboard bb_pattern = Bitboard::EMPTY;
    for (Square sq : BBSquareScan(bb)) {
        bb_pattern |= static_cast<Bitboard>((bits & 1) << idx(sq));
        bits >>= 1;
    }
    return bb_pattern;
}

template<Piece slider_type> requires is_bishop_or_rook<slider_type>
static Bitboard generate_slider_attacks(Bitboard bb_from, Bitboard bb_blockers) {
    Bitboard bb_attacks = Bitboard::EMPTY;
    for (Direction dir : SLIDER_DIRECTIONS<slider_type>) {
        Bitboard bb_bit = bb_shift<true>(bb_from, dir);
        while (nonzero(bb_bit)) {
            bb_attacks |= bb_bit;
            bb_bit = bb_shift<true>(bb_bit & ~bb_blockers, dir);
        }
    }
    return bb_attacks;
}

template<Piece slider_piece>
void find_magics(std::ostream& out) {
    static_assert(
        slider_piece == Piece::ROOK || slider_piece == Piece::BISHOP,
        "magics only available for rook and bishop"
    );
    for (Square sq : iter<Square>) {
        Bitboard bb_attack_mask = bb_slider_attack_mask<slider_piece>(sq);
        size_t table_size = (1ULL << popcount(bb_attack_mask));
        std::vector<MagicEntry> attack_sets;
        for (size_t bits = 0; bits < table_size; ++bits) {
            attack_sets.emplace_back(assign_bits(bb_attack_mask, bits), bb_attack_mask);
        }
        MagicHash magic = find_magic(attack_sets);
        #ifndef NDEBUG
        auto stats = magic.check_magic(attack_sets);
        assert(stats.valid);
        assert(!stats.mod_needed);
        #endif
        out << "            " << magic << (sq != Square::H8 ? "," : "") << std::endl;
    }
}

const char* PART_ONE = R"(#pragma once

// File automatically generated by tools/make_magic.cpp

#include "types.hpp"

namespace bears_chess {

template<Piece slider_piece> constexpr auto MAGICS = []() -> std::array<uint64_t, num_of<Square>> {
    static_assert(
        slider_piece == Piece::ROOK || slider_piece == Piece::BISHOP,
        "magics available only for slider_piece of ROOK or BISHOP"
    );
    if constexpr (slider_piece == Piece::ROOK) {
        return {
)";

const char* PART_TWO = R"(        };
    } else {
        return {
)";

const char* PART_THREE = R"(        };
    }
}();

}    // namespace bears_chess

)";

int main() {
    std::ofstream fout("../../include/magics.hpp");
    // auto& fout = std::cout;

    fout << PART_ONE;
    find_magics<Piece::ROOK>(fout);
    fout << PART_TWO;
    find_magics<Piece::BISHOP>(fout);
    fout << PART_THREE << std::flush;

    return 0;
}
