#include <ranges>
#include <iostream>
#include <fstream>
#include <random>
#include <vector>

#include "bitboard.hpp"
#include "board_utils.hpp"
#include "magics.hpp"

using namespace bears_chess;

class MagicHash {
    public:
        using scale_t = std::underlying_type_t<Bitboard>;

        struct Stats {
            bool valid;
            uint64_t max_hash;
            bool mod_needed;
        };

        constexpr MagicHash(scale_t _scale, size_t _target_size) :
            scale(_scale), target_size(_target_size), shift(64 - log2(target_size))
        {}

        template<bool ApplyMod=true>
        constexpr size_t apply(Bitboard bb_blockers) const {
            size_t hash = static_cast<size_t>((static_cast<scale_t>(bb_blockers) * scale) >> shift);
            if constexpr (ApplyMod) {
                hash %= target_size;
            }
            return hash;
        }

        Stats check_magic(const std::vector<AttackSet>& attack_sets) const {
            const size_t size = attack_sets.size();
            std::unordered_map<size_t, Bitboard> hash_to_moves;

            Stats result{false, 0, false};
            for (const auto& attack_set : attack_sets) {
                size_t hash_nomod = apply<false>(attack_set.bb_blockers);
                size_t hash = hash_nomod % target_size;

                result.mod_needed = result.mod_needed || (hash != hash_nomod);

                if (hash_to_moves.count(hash)) {
                    // if the hash exists, ensure the moves are the same
                    if (hash_to_moves[hash] != attack_set.bb_moves)
                    result.valid = false;
                        return result;
                } else {
                    // otherwise, store the hash and the moves
                    hash_to_moves[hash] = attack_set.bb_moves;
                }
                result.max_hash = std::max(result.max_hash, hash);
            }

            result.valid = true;
            return result;
        }

        friend std::ostream& operator<<(std::ostream&, const MagicHash&);
    private:
        const scale_t scale;
        const int8_t shift;
        const size_t target_size;
};

std::ostream& operator<<(std::ostream& out, const MagicHash& hash) {
    std::ios::fmtflags original_flags = out.flags();
    char original_fill = out.fill();

    out << "MagicHash(0x" << std::hex << std::setw(16) << std::setfill('0') << hash.scale << "ULL, "
        << std::dec << static_cast<int>(hash.shift) << ", " << hash.target_size << ")";

    out.flags(original_flags);
    out.fill(original_fill);

    return out;
}

MagicHash find_magic(const std::vector<AttackSet>& attack_sets) {
    std::mt19937_64 rng(std::random_device{}());
    std::uniform_int_distribution<uint64_t> dist;

    size_t size = attack_sets.size();

    while (true) {
        MagicHash magic = MagicHash(dist(rng) & dist(rng) & dist(rng), size);
        MagicHash::Stats stats = magic.check_magic(attack_sets);
        if (stats.valid) {
            return magic;
        }
    }
}

int main() {
    // std::ofstream fout("../../include/magic_defs.hpp");
    auto& fout = std::cout;

    fout << "#pragma once\n"
         << "\n"
         << "// File automatically generated by " << __FILE__ << "\n"
         << "\n"
         << "#include \"types.hpp\"\n"
         << "\n"
         << "namespace bears_chess {\n"
         << std::endl;
    fout << "constexpr std::array<MagicInfo, num_of<Square>> ROOK_MAGICS = {" << std::endl;
    for (Square sq : iter<Square>) {
        auto attack_set_view = rook_attack_view(sq);
        const std::vector<AttackSet> attack_sets(attack_set_view.begin(), attack_set_view.end());
        MagicHash magic = find_magic(attack_sets);
        auto stats = magic.check_magic(attack_sets);
        fout << "    square=" << sq << ", valid=" << (stats.valid ? "true" : "FALSE")
             << ", mod_needed=" << (stats.mod_needed ? "TRUE" : "false")
             << ", max_hash=" << stats.max_hash << std::endl;
        
        fout << "    " << magic << (sq != Square::H8 ? "," : "") << std::endl;
    }
    fout << "};" << std::endl;

    fout << "constexpr std::array<MagicInfo, num_of<Square>> BISHOP_MAGICS = {" << std::endl;
    for (Square sq : iter<Square>) {
        auto attack_set_view = bishop_attack_view(sq);
        const std::vector<AttackSet> attack_sets(attack_set_view.begin(), attack_set_view.end());
        MagicHash magic = find_magic(attack_sets);
        auto stats = magic.check_magic(attack_sets);
        fout << "    square=" << sq << ", valid=" << (stats.valid ? "true" : "FALSE")
             << ", mod_needed=" << (stats.mod_needed ? "TRUE" : "false")
             << ", max_hash=" << stats.max_hash << std::endl;
        fout << "    " << magic << (sq != Square::H8 ? "," : "") << std::endl;
    }
    fout << "};" << std::endl;

    fout << "\n"
         << "}    // namespace bears_chess\n"
         << std::endl;

    return 0;
}
